# 2024/11/05 - hmaarrfk
# I'm building for a few versions of pytorch to allow users
# to workaround https://github.com/conda-forge/hdf5-feedstock/issues/240
pytorch:
  - 2.4.1
  - 2.5.1

libtorch:
  - 2.4.1
  - 2.5.1

zip:
  -
    - pytorch
    - libtorch
