github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
build_platform:
  osx_arm64: osx_64
os_version:
  linux_64: alma8
  linux_aarch64: alma8
  linux_ppc64le: alma8
test: native_and_emulated
conda_forge_output_validation: true
